### ISSUE TITLE
Timezone format "XXX"

### ISSUE THREAD

**Issue by MeiCarmen** [MeiCarmen/mpp-ios-android#12]

**Comment by harry48225** [comment]
XXX appends a Z to the time for 'Zulu time' (UTC) This should be equivalent to the current scheme of appending +00:00 to the time. However when the api gets queried with this it returns fewer trains than when using +00:00. However assuming localTime = UTC time + 1 hour "(localTime)Z" gives identical results to "(utcTime)+00:00" which is unexpected behaviour, "(localTime-1 hour)Z" should give the same results as "(utcTime)+00:00". Also the API doesn't seem to implement the other timezone codes "A,B,C,...,Y"

It doesn't seem that the API is interpreting the timezone correctly.
